default:
  tags:
    - zeta
  services:
    - name: docker:24.0.5-dind
      variables:
        HEALTHCHECK_TCP_PORT: "2376"

.image_template: &image_template
  image: $CI_REGISTRY/zeta/devops/ci-images/docker:24.0.5-zeta-0
  needs: []
  rules:
    - if: $RUN_IMAGE_ONLY == "true"
    - when: never

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: $DOCKER_TLS_CERTDIR/client
  DOCKER_TLS_VERIFY: "1"

build-image-android:
  <<: *image_template
  stage: image_build
  script:
    - echo "CONTAINER_VERSION is set to $CONTAINER_VERSION"
    - printf "%s" "$CI_DEPENDENCY_PROXY_PASSWORD" | docker login "$CI_DEPENDENCY_PROXY_SERVER" -u "$CI_DEPENDENCY_PROXY_USER" --password-stdin
    - printf "%s" "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t "$CI_REGISTRY"/zeta/zeta-client/zeta-sdk/android-image:$CONTAINER_VERSION -f Dockerfile.android .
    - docker push "$CI_REGISTRY"/zeta/zeta-client/zeta-sdk/android-image:$CONTAINER_VERSION

build-image-ios:
  <<: *image_template
  stage: image_build
  script:
    - printf "%s" "$CI_DEPENDENCY_PROXY_PASSWORD" | docker login "$CI_DEPENDENCY_PROXY_SERVER" -u "$CI_DEPENDENCY_PROXY_USER" --password-stdin
    - printf "%s" "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t "$CI_REGISTRY"/zeta/zeta-client/zeta-sdk/ios-image:$CONTAINER_VERSION -f Dockerfile.ios .
    - docker push "$CI_REGISTRY"/zeta/zeta-client/zeta-sdk/ios-image:$CONTAINER_VERSION

build-image-jvm:
  <<: *image_template
  stage: image_build
  script:
    - printf "%s" "$CI_DEPENDENCY_PROXY_PASSWORD" | docker login "$CI_DEPENDENCY_PROXY_SERVER" -u "$CI_DEPENDENCY_PROXY_USER" --password-stdin
    - printf "%s" "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t "$CI_REGISTRY"/zeta/zeta-client/zeta-sdk/jvm-image:$CONTAINER_VERSION -f Dockerfile.jvm .
    - docker push "$CI_REGISTRY"/zeta/zeta-client/zeta-sdk/jvm-image:$CONTAINER_VERSION

build-package-testdriver:
  <<: *image_template
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/eclipse-temurin:21-jdk
  stage: image_build
  script:
    - ./gradlew clean jar copyRuntimeLibs
  artifacts:
    expire_in: 1 week
    paths:
      - "**/build/libs/*.jar"
      - "**/build/runtime-libs/*.jar"

build-image-testdriver:
  <<: *image_template
  stage: image_build
  needs: [build-package-testdriver]
  script:
    - printf "%s" "$CI_DEPENDENCY_PROXY_PASSWORD" | docker login "$CI_DEPENDENCY_PROXY_SERVER" -u "$CI_DEPENDENCY_PROXY_USER" --password-stdin
    - printf "%s" "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t "$CI_REGISTRY"/zeta/zeta-client/zeta-sdk/testdriver-image:$CONTAINER_VERSION -f zeta-testdriver/Dockerfile .
    - docker push "$CI_REGISTRY"/zeta/zeta-client/zeta-sdk/testdriver-image:$CONTAINER_VERSION
