FILES=NOTICE,LICENSE
PCR_ID=23
SERVER_PORT=8081
ALLOWED_EXECUTABLES=/snap/postman/360/usr/share/postman/postman
ENABLE_FILE_INTEGRITY=true
ENABLE_QUOTE=true
ENABLE_PCR_LOG=true
ENABLE_EK_CERTIFICATE=true
ENABLE_PROCESS_ORIGIN=true
